apiVersion: v1
kind: PersistentVolume
metadata:
  name: wdw-wait-times-db
  labels:
    app: wdw-wait-times
    use: db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /k3s/wdw-wait-times